### PR TITLE
Downgraded NLog.AirBrake to use .Net 2.0

### PR DESCRIPTION
**Pull request by LinkExe**
Removed linq and .net 3.5 required items. Added a couple tricks to get it to run under 2.0. Passes Xunit tests.

### CODE REVIEW

**Comment by Iristyle** [comment]
Hey @DonMcNamara  you want to add a second set of eyes here as well?

This looks pretty great for your first pull.  

The only thing is that the build now creates _only_ a 2.0 version, rather than us having both a .NET 4 and .NET 2 version to ship.  As you've seen with the mods you made to packages.config, a NuGet package may contain multiple versions that are targeted at the correct CLR.

There can be issues loading .NET 2 assemblies into a .NET 4 process.  There's a good explanation and links to a few of these via this [SO post](http://stackoverflow.com/questions/3267491/when-linking-a-net-2-0-managed-assembly-from-a-net-4-0-application-which-fram)

So I would generally favor shipping a .NET 4 and a .NET 2 version, rather than doing a blanket .NET 2 compatible version. I'm fine with the changes made to remove the LINQ code, as this makes it so we don't have to `#ifdef` anything... which is a good thing.

It's mostly an issue of having 2 build configs -- one for .NET 2 and another for .NET 4.  And then making those both build and together create the NuGet package.

**Comment by DonMcNamara** [comment]
So, the changes made are to the sharpbrake code, which are not covered by our unit tests. If possible, it might be worthwhile trying to run the sharpbrake unit tests against these changes.

**Comment by Iristyle** [comment]
Also a great point ;0

**Comment by LinkExe** [comment]
I'll add sharpbrake tests, but do you want it to target 2 and 4? It'd be easier for me to make it 2 and 3.5 because that's what the last commit was at.

**Comment by Iristyle** [comment]
Yeah, so I think we should go net20 and net40 ... net35 is the same CLR (2.0) as .NET 2.0.  The only differences are with available libraries (which we don't care about) and compiler changes (which you have mitigated already).

**Comment by LinkExe** [comment]
@Iristyle Am I headed in the right direction with my last commits?

**Comment by Iristyle** [comment]
Can you see now how the diffs are much more descriptive about what changes were performed?

**Pull request merged**
