### PR TITLE
Remove ExtensionAttribute class to resolve warnings.

### PR DESCRIPTION
**Pull request by DonMcNamara**
In .Net 4.0 projects, the ExtensionsAttribute class was causing
compiler warnings. In order to remove that class, all extension
method calls were converted to simple static method calls.

### CODE REVIEW

**Comment by Iristyle** [comment]
Ok.. so I blasted a bunch of this out on HipChat... but will put here for posterity.  3 possible options for doing the conditional include of Extensions.cs

### Option 1

In the `csproj`, extend the `DefineConstants` MSBuild property.

``` xml
<PropertyGroup>
  <DefineConstants Condition="'$(TargetFrameworkVersion)' == 'v2.0'>$(DefineConstants);NET20</DefineConstants>
</PropertyGroup>
```

**It is critical that this appears after the other `<PropertyGroup>` nodes that defined the debug / release builds**

Then conditionally include the Extension stuff _only_ for .NET 2.

``` csharp
#if NET20
namespace System.Runtime.CompilerServices
    //This bit of code lets our project compile under .NET 2.0
{
   class ExtensionAttribute : Attribute
   {

   }
}

namespace NLog.AirBrake
{

    public static class ExtensionHolder
    {

    }
}
#endif
```

### Option 2

Do the same thing as above, except pass along the constants at the command line to msbuild.

So in [default.ps1](https://github.com/EastPoint/NLog.AirBrake/blob/master/build/default.ps1#L31), instead of

``` powershell
exec { msbuild build.proj }
```

You use 

``` powershell
exec { msbuild build.proj /p:DefineConstants="TRACE;CROMAG;NET20" }
```

Then the above `#if` / `#endif` block remains the same.

### Option 3

The most sneaky, but smallest change.  Conditionally include the `Extensions.cs` file [here in the csproj](https://github.com/EastPoint/NLog.AirBrake/blob/master/src/NLog.AirBrake/NLog.AirBrake.csproj#L58)

Instead of 

``` xml
<Compile Include="Extensions.cs" />
```

You have 

``` xml
<Compile Include="Extensions.cs" Condition="'$(TargetFrameworkVersion)' == 'v2.0' />
```

You don't need to `#if` anything, since the default target in the csproj file that you'd build in VS has TargetFrameworkVersion v2.0.  During the Psake build for .NET 4, this file would be excluded.

No VS support here... but since we only have a single project file targeting .NET 2.0, this might not be a big deal.

**Comment by Iristyle** [comment]
Ok.. I opted for version 3... took a couple more minor changes more than I expected ;0  I will probably squash all 3 commits down into 1, since I was just screwing around in Ace editor.

**Comment by DonMcNamara** [comment]
I was messing around with option 3 earlier... I got the main project to work fine, but gave up on the unit test assembly. This is what I had:

```
    <Reference Include="NLog">
      <HintPath Condition=" '$(TargetFrameworkVersion)' == 'v2.0' ">..\packages\NLog.2.0.0.2000\lib\net20\NLog.dll</HintPath>
      <HintPath Condition=" '$(TargetFrameworkVersion)' == 'v4.0' ">..\packages\NLog.2.0.0.2000\lib\net40\NLog.dll</HintPath>
    </Reference>
```

```
<Compile Include="Extensions.cs" Condition=" '$(TargetFrameworkVersion)' == 'v2.0' " />
```

**Comment by DonMcNamara** [comment]
Also, I think it is okay to dump the test app now, if that simplifies the build process.

**Comment by Iristyle** [comment]
Yeah, my changes build and it ships, etc... but I noticed in the build log that we're still getting warnings on the Extension redefinition.. because... NLog built for .NET 2.0 seems to already include it.

```
CSC : warning CS1685: The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'd:\JenkinsHome\workspace\NLog.AirBrake\src\packages\NLog.2.0.0.2000\lib\net20\NLog.dll' [D:\JenkinsHome\workspace\NLog.AirBrake\src\NLog.AirBrake.TestApp\NLog.AirBrake.TestApp.csproj]
```

Their class is in [CompilerAttributes](https://github.com/NLog/NLog/blob/master/src/NLog/Internal/CompilerAttributes.cs)

So I'm not sure why @LinkExe even included that in the first place... it wasn't necessary.  Maybe this had something to do with compiling against .NET 2, and referencing the .NET 4 NLog or something, where it wasn't defined.. :confused: 

So in any event, it appears that was an accident, and we don't need that file at all.  I will verify locally before I do a new pull or anything.

**Comment by Iristyle** [comment]
Oh wait.. their attribute is internal... that must have been why ;0

**Comment by Iristyle** [comment]
Closing this ... if we want to ditch the test app part, we can do that.

**Pull request closed without merging**
